....

== user and group add

[root@harshalchg-1 ~]# yum install pssh
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos4.zswap.net
 * epel: ord.mirror.rackspace.com
 * extras: centos4.zswap.net
 * updates: centos4.zswap.net
Resolving Dependencies
--> Running transaction check
---> Package pssh.noarch 0:2.3.1-5.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==========================================================================================================================================================
 Package                           Arch                                Version                                    Repository                         Size
==========================================================================================================================================================
Installing:
 pssh                              noarch                              2.3.1-5.el7                                epel                               49 k

Transaction Summary
==========================================================================================================================================================
Install  1 Package

Total download size: 49 k
Installed size: 115 k
Is this ok [y/d/N]: y
Downloading packages:
pssh-2.3.1-5.el7.noarch.rpm                                                                                                        |  49 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : pssh-2.3.1-5.el7.noarch                                                                                                                1/1 
  Verifying  : pssh-2.3.1-5.el7.noarch                                                                                                                1/1 

Installed:
  pssh.noarch 0:2.3.1-5.el7                                                                                                                               

Complete!
[root@harshalchg-1 ~]# pssh
Usage: pssh [OPTIONS] command [...]

pssh: error: Command not specified.
[root@harshalchg-1 ~]# pssh -v -h ~/clhost -A -i "-O StrictHostKeyChecking=no" -l root "touch abc.txt"
Warning: do not enter your password if anyone else has superuser
privileges or access to your account.
Password: 
[1] 06:25:45 [SUCCESS] 172.31.115.50
Stderr: Warning: Permanently added '172.31.115.50' (ECDSA) to the list of known hosts.
pssh-askpass received prompt: "root@172.31.115.50's password: "
[2] 06:25:46 [SUCCESS] 172.31.112.18
Stderr: Warning: Permanently added '172.31.112.18' (ECDSA) to the list of known hosts.
pssh-askpass received prompt: "root@172.31.112.18's password: "
[3] 06:25:46 [SUCCESS] 172.31.116.121
Stderr: Warning: Permanently added '172.31.116.121' (ECDSA) to the list of known hosts.
pssh-askpass received prompt: "root@172.31.116.121's password: "
[4] 06:25:46 [SUCCESS] 172.31.115.37
Stderr: Warning: Permanently added '172.31.115.37' (ECDSA) to the list of known hosts.
pssh-askpass received prompt: "root@172.31.115.37's password: "
[5] 06:25:46 [SUCCESS] 172.31.115.32
Stderr: Warning: Permanently added '172.31.115.32' (ECDSA) to the list of known hosts.
pssh-askpass received prompt: "root@172.31.115.32's password: "
[root@harshalchg-1 ~]# pssh -v -h ~/clhost -A -i "useradd --uid 1984 bonnie"
Warning: do not enter your password if anyone else has superuser
privileges or access to your account.
Password: 
[1] 06:27:55 [SUCCESS] 172.31.112.18
Stderr: pssh-askpass received prompt: "root@172.31.112.18's password: "
[2] 06:27:55 [SUCCESS] 172.31.115.32
Stderr: pssh-askpass received prompt: "root@172.31.115.32's password: "
[3] 06:27:55 [SUCCESS] 172.31.115.50
Stderr: pssh-askpass received prompt: "root@172.31.115.50's password: "
[4] 06:27:55 [SUCCESS] 172.31.116.121
Stderr: pssh-askpass received prompt: "root@172.31.116.121's password: "
[5] 06:27:55 [SUCCESS] 172.31.115.37
Stderr: pssh-askpass received prompt: "root@172.31.115.37's password: "
[root@harshalchg-1 ~]# pssh -v -h ~/clhost -A -i "useradd --uid 1985 clyde"
Warning: do not enter your password if anyone else has superuser
privileges or access to your account.
Password: 
[1] 06:28:38 [SUCCESS] 172.31.112.18
Stderr: pssh-askpass received prompt: "root@172.31.112.18's password: "
[2] 06:28:38 [SUCCESS] 172.31.116.121
Stderr: pssh-askpass received prompt: "root@172.31.116.121's password: "
[3] 06:28:38 [SUCCESS] 172.31.115.32
Stderr: pssh-askpass received prompt: "root@172.31.115.32's password: "
[4] 06:28:38 [SUCCESS] 172.31.115.37
Stderr: pssh-askpass received prompt: "root@172.31.115.37's password: "
[5] 06:28:38 [SUCCESS] 172.31.115.50
Stderr: pssh-askpass received prompt: "root@172.31.115.50's password: "
[root@harshalchg-1 ~]# groupadd

[root@harshalchg-1 ~]# pssh -v -h ~/clhost -A -i "groupadd rebel"
Warning: do not enter your password if anyone else has superuser
privileges or access to your account.
Password: 
[1] 06:30:26 [SUCCESS] 172.31.112.18
Stderr: pssh-askpass received prompt: "root@172.31.112.18's password: "
[2] 06:30:26 [SUCCESS] 172.31.115.50
Stderr: pssh-askpass received prompt: "root@172.31.115.50's password: "
[3] 06:30:26 [SUCCESS] 172.31.115.32
Stderr: pssh-askpass received prompt: "root@172.31.115.32's password: "
[4] 06:30:26 [SUCCESS] 172.31.115.37
Stderr: pssh-askpass received prompt: "root@172.31.115.37's password: "
[5] 06:30:26 [SUCCESS] 172.31.116.121
Stderr: pssh-askpass received prompt: "root@172.31.116.121's password: "
[root@harshalchg-1 ~]# pssh -v -h ~/clhost -A -i "groupadd cause"
Warning: do not enter your password if anyone else has superuser
privileges or access to your account.
Password: 
[1] 06:30:46 [SUCCESS] 172.31.112.18
Stderr: pssh-askpass received prompt: "root@172.31.112.18's password: "
[2] 06:30:46 [SUCCESS] 172.31.115.50
Stderr: pssh-askpass received prompt: "root@172.31.115.50's password: "
[3] 06:30:46 [SUCCESS] 172.31.115.32
Stderr: pssh-askpass received prompt: "root@172.31.115.32's password: "
[4] 06:30:46 [SUCCESS] 172.31.116.121
Stderr: pssh-askpass received prompt: "root@172.31.116.121's password: "
[5] 06:30:46 [SUCCESS] 172.31.115.37
Stderr: pssh-askpass received prompt: "root@172.31.115.37's password: "

[root@harshalchg-1 ~]# pssh -v -h ~/clhost -A -i "usermod --gid rebel bonnie"
Warning: do not enter your password if anyone else has superuser
privileges or access to your account.
Password: 
[1] 06:32:49 [SUCCESS] 172.31.112.18
Stderr: pssh-askpass received prompt: "root@172.31.112.18's password: "
[2] 06:32:49 [SUCCESS] 172.31.116.121
Stderr: pssh-askpass received prompt: "root@172.31.116.121's password: "
[3] 06:32:49 [SUCCESS] 172.31.115.32
Stderr: pssh-askpass received prompt: "root@172.31.115.32's password: "
[4] 06:32:49 [SUCCESS] 172.31.115.37
Stderr: pssh-askpass received prompt: "root@172.31.115.37's password: "
[5] 06:32:49 [SUCCESS] 172.31.115.50
Stderr: pssh-askpass received prompt: "root@172.31.115.50's password: "
[root@harshalchg-1 ~]# pssh -v -h ~/clhost -A -i "usermod --gid cause clyde"
Warning: do not enter your password if anyone else has superuser
privileges or access to your account.
Password: 
[1] 06:33:28 [SUCCESS] 172.31.112.18
Stderr: pssh-askpass received prompt: "root@172.31.112.18's password: "
[2] 06:33:28 [SUCCESS] 172.31.115.50
Stderr: pssh-askpass received prompt: "root@172.31.115.50's password: "
[3] 06:33:28 [SUCCESS] 172.31.115.32
Stderr: pssh-askpass received prompt: "root@172.31.115.32's password: "
[4] 06:33:28 [SUCCESS] 172.31.115.37
Stderr: pssh-askpass received prompt: "root@172.31.115.37's password: "
[5] 06:33:28 [SUCCESS] 172.31.116.121
Stderr: pssh-askpass received prompt: "root@172.31.116.121's password: "

[root@harshalchg-1 etc]# cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
operator:x:11:0:operator:/root:/sbin/nologin
games:x:12:100:games:/usr/games:/sbin/nologin
ftp:x:14:50:FTP User:/var/ftp:/sbin/nologin
nobody:x:99:99:Nobody:/:/sbin/nologin
systemd-network:x:192:192:systemd Network Management:/:/sbin/nologin
dbus:x:81:81:System message bus:/:/sbin/nologin
polkitd:x:999:998:User for polkitd:/:/sbin/nologin
ntp:x:38:38::/etc/ntp:/sbin/nologin
sshd:x:74:74:Privilege-separated SSH:/var/empty/sshd:/sbin/nologin
postfix:x:89:89::/var/spool/postfix:/sbin/nologin
chrony:x:998:996::/var/lib/chrony:/sbin/nologin
centos-user:x:1000:1001::/home/centos-user:/bin/bash
systest:x:2000:2000::/home/systest:/bin/bash
nscd:x:28:28:NSCD Daemon:/:/sbin/nologin
jenkins:x:2001:2001:jenkins:/var/lib/jenkins:/bin/bash
bonnie:x:1984:2002::/home/bonnie:/bin/bash
clyde:x:1985:2003::/home/clyde:/bin/bash

== Instances

GCP
		
harshalchg-2.gce.cloudera.com	harshalchg-2	172.31.112.18
harshalchg-4.gce.cloudera.com	harshalchg-4	172.31.115.32
harshalchg-5.gce.cloudera.com	harshalchg-5	172.31.115.37
harshalchg-1.gce.cloudera.com	harshalchg-1	172.31.115.50
harshalchg-3.gce.cloudera.com	harshalchg-3	172.31.116.121

Centos 7.5

[root@harshalchg-1 etc]# df
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/sda1      104844988 2000436 102844552   2% /
devtmpfs         6577648       0   6577648   0% /dev
tmpfs            6585388       0   6585388   0% /dev/shm
tmpfs            6585388    8564   6576824   1% /run
tmpfs            6585388       0   6585388   0% /sys/fs/cgroup
tmpfs            1317080       0   1317080   0% /run/user/0

[root@harshalchg-1 etc]# yum repolist enabled
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos4.zswap.net
 * epel: ord.mirror.rackspace.com
 * extras: centos4.zswap.net
 * updates: centos4.zswap.net
repo id                                                      repo name                                                                              status
base/7/x86_64                                                CentOS-7 - Base                                                                        10097
epel/x86_64                                                  Extra Packages for Enterprise Linux 7 - x86_64                                         13485
extras/7/x86_64                                              CentOS-7 - Extras                                                                        305
google-cloud-compute                                         Google Cloud Compute                                                                      11
google-cloud-sdk                                             Google Cloud SDK                                                                        1032
updates/7/x86_64                                             CentOS-7 - Updates                                                                       953
repolist: 25883

[root@harshalchg-1 etc]# cat /etc/passwd | grep bonnie
bonnie:x:1984:2002::/home/bonnie:/bin/bash
[root@harshalchg-1 etc]# cat /etc/passwd | grep clyde
clyde:x:1985:2003::/home/clyde:/bin/bash

[root@harshalchg-1 etc]# getent group rebel
rebel:x:2002:

[root@harshalchg-1 etc]# getent passwd bonnie
bonnie:x:1984:2002::/home/bonnie:/bin/bash

== MARIADB Install

setup vm swampiness and transparent hugepage support
resolve all hosts

[root@harshalchg-1 etc]# pssh -v -h ~/clhost -l root -A -i "sysctl vm.swappiness=1"
Warning: do not enter your password if anyone else has superuser
privileges or access to your account.
Password: 
[1] 06:48:50 [SUCCESS] 172.31.115.50
vm.swappiness = 1
Stderr: pssh-askpass received prompt: "root@172.31.115.50's password: "
[2] 06:48:50 [SUCCESS] 172.31.112.18
vm.swappiness = 1
Stderr: pssh-askpass received prompt: "root@172.31.112.18's password: "
[3] 06:48:50 [SUCCESS] 172.31.115.32
vm.swappiness = 1
Stderr: pssh-askpass received prompt: "root@172.31.115.32's password: "
[4] 06:48:50 [SUCCESS] 172.31.116.121
vm.swappiness = 1
Stderr: pssh-askpass received prompt: "root@172.31.116.121's password: "
[5] 06:48:50 [SUCCESS] 172.31.115.37
vm.swappiness = 1
Stderr: pssh-askpass received prompt: "root@172.31.115.37's password: "
[root@harshalchg-1 etc]# pssh -v -h ~/clhost  -A -i -l root "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
Warning: do not enter your password if anyone else has superuser
privileges or access to your account.
Password: 
[1] 06:49:47 [SUCCESS] 172.31.112.18
Stderr: pssh-askpass received prompt: "root@172.31.112.18's password: "
[2] 06:49:47 [SUCCESS] 172.31.115.50
Stderr: pssh-askpass received prompt: "root@172.31.115.50's password: "
[3] 06:49:47 [SUCCESS] 172.31.115.32
Stderr: pssh-askpass received prompt: "root@172.31.115.32's password: "
[4] 06:49:47 [SUCCESS] 172.31.115.37
Stderr: pssh-askpass received prompt: "root@172.31.115.37's password: "
[5] 06:49:47 [SUCCESS] 172.31.116.121
Stderr: pssh-askpass received prompt: "root@172.31.116.121's password: "


[root@harshalchg-1 etc]# scp /etc/hosts root@harshalchg-2:/etc/hosts
The authenticity of host 'harshalchg-2 (172.31.112.18)' can't be established.
ECDSA key fingerprint is SHA256:swxupmru8Bbn0JUuuN8dTqHIMbRD9wz0LkYPXbyZGHk.
ECDSA key fingerprint is MD5:0a:7a:73:eb:17:4f:f6:d0:3a:bf:23:dc:a3:d7:a6:68.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'harshalchg-2' (ECDSA) to the list of known hosts.
root@harshalchg-2's password: 
Permission denied, please try again.
root@harshalchg-2's password: 
Permission denied, please try again.
root@harshalchg-2's password: 
hosts                                                                                                                   100%  582   479.3KB/s   00:00    
[root@harshalchg-1 etc]# scp /etc/hosts root@harshalchg-3:/etc/hosts
The authenticity of host 'harshalchg-3 (172.31.116.121)' can't be established.
ECDSA key fingerprint is SHA256:8dMtX+TCr1Ime1vyYxa1PQwZLKzbi/J5rK95CALld18.
ECDSA key fingerprint is MD5:9a:4f:36:15:c4:df:3c:29:e4:34:21:4f:83:25:8c:56.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'harshalchg-3' (ECDSA) to the list of known hosts.
root@harshalchg-3's password: 
hosts                                                                                                                   100%  582   353.6KB/s   00:00    
[root@harshalchg-1 etc]# scp /etc/hosts root@harshalchg-4:/etc/hosts
The authenticity of host 'harshalchg-4 (172.31.115.32)' can't be established.
ECDSA key fingerprint is SHA256:lvsxGTTDWru5u0v7+2Jfb1fKt1fLKIvWCWH6I7M7aQg.
ECDSA key fingerprint is MD5:20:79:9f:cd:d2:97:e1:40:41:b7:4d:ef:c5:dd:c0:f3.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'harshalchg-4' (ECDSA) to the list of known hosts.
root@harshalchg-4's password: 
hosts                                                                                                                   100%  582   404.7KB/s   00:00    
[root@harshalchg-1 etc]# scp /etc/hosts root@harshalchg-5:/etc/hosts
The authenticity of host 'harshalchg-5 (172.31.115.37)' can't be established.
ECDSA key fingerprint is SHA256:572tEGDC+8wqlvlb/LMcDkq/LLkl0tDFrST2eLqQPlo.
ECDSA key fingerprint is MD5:6a:a7:c9:a3:25:91:3f:51:9a:db:08:d3:48:36:ef:af.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'harshalchg-5' (ECDSA) to the list of known hosts.
root@harshalchg-5's password: 
hosts                                                                                                                   100%  582   266.6KB/s   00:00    


[root@harshalchg-1 etc]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
172.31.115.50 harshalchg-1.gce.cloudera.com harshalchg-1  # Added by Google
169.254.169.254 metadata.google.internal  # Added by Google
172.31.112.18	harshalchg-2.gce.cloudera.com	harshalchg-2
172.31.115.32	harshalchg-4.gce.cloudera.com	harshalchg-4
172.31.115.37	harshalchg-5.gce.cloudera.com	harshalchg-5
172.31.115.50	harshalchg-1.gce.cloudera.com	harshalchg-1
172.31.116.121	harshalchg-3.gce.cloudera.com	harshalchg-3











