....

== CM log 

[root@harshalchg-4 ~]# systemctl start cloudera-scm-server
[root@harshalchg-4 ~]# tail -f /var/log/cloudera-scm-server/cloudera-scm-server.log
2019-12-06 08:48:47,690 INFO main:com.cloudera.server.cmf.Main: ================================================================================
2019-12-06 08:48:47,713 INFO main:com.cloudera.server.cmf.Main: Starting SCM Server. JVM Args: [-Dlog4j.configuration=file:/etc/cloudera-scm-server/log4j.properties, -Dfile.encoding=UTF-8, -Dcmf.root.logger=INFO,LOGFILE, -Dcmf.log.dir=/var/log/cloudera-scm-server, -Dcmf.log.file=cloudera-scm-server.log, -Dcmf.jetty.threshhold=WARN, -Dcmf.schema.dir=/opt/cloudera/cm/schema, -Djava.awt.headless=true, -Djava.net.preferIPv4Stack=true, -Dpython.home=/opt/cloudera/cm/python, -XX:+HeapDumpOnOutOfMemoryError, -Xmx2G, -XX:MaxPermSize=256m, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/tmp, --add-opens=java.base/java.nio=ALL-UNNAMED, --add-opens=java.base/sun.nio.ch=ALL-UNNAMED, --add-opens=java.base/sun.nio.cs=ALL-UNNAMED, --add-opens=java.base/java.lang=ALL-UNNAMED, --add-opens=java.base/java.lang.reflect=ALL-UNNAMED, --add-opens=java.desktop/java.awt.font=ALL-UNNAMED, --add-opens=java.base/java.util.regex=ALL-UNNAMED, --add-opens=java.base/java.util.zip=ALL-UNNAMED, --add-opens=java.base/java.util=ALL-UNNAMED, --add-opens=java.base/java.net=ALL-UNNAMED, --add-opens=java.base/java.io=ALL-UNNAMED, --add-opens=java.base/java.security=ALL-UNNAMED, --add-opens=java.base/java.text=ALL-UNNAMED, --add-opens=java.base/javax.crypto=ALL-UNNAMED, -XX:OnOutOfMemoryError=kill -9 %p], Args: [], Version: 6.3.0 (#1281944 built by jenkins on 20190719-0609 git: 5b793e9c9cb3f40b3912044aac00abb635183191)

2019-12-06 08:50:50,668 INFO WebServerImpl:org.eclipse.jetty.server.AbstractConnector: Started ServerConnector@47fbf296{HTTP/1.1,[http/1.1]}{0.0.0.0:7180}
2019-12-06 08:50:50,685 INFO WebServerImpl:org.eclipse.jetty.server.Server: Started @123802ms
2019-12-06 08:50:50,685 INFO WebServerImpl:com.cloudera.server.cmf.WebServerImpl: Started Jetty server.
2019-12-06 08:50:54,656 ERROR ParcelUpdateService:com.cloudera.parcel.components.ParcelDownloaderImpl: Failed to download manifest. Status code: 404 URI: https://archive.cloudera.com/sqoop-teradata-connector1/1.7.1c6/manifest.json/
2019-12-06 08:51:14,651 INFO scm-web-95:com.cloudera.server.web.cmf.CMFUserDetailsService: First user 'admin' logging in.
2019-12-06 08:51:14,738 INFO scm-web-95:com.cloudera.server.web.cmf.AuthenticationSuccessEventListener: Authentication success for user: 'admin' from 10.96.93.76


== DB Properties
[root@harshalchg-4 ~]# find / -name db.properties
/etc/cloudera-scm-server/db.properties
[root@harshalchg-4 ~]# cat /etc/cloudera-scm-server/db.properties
# Auto-generated by scm_prepare_database.sh on Fri Dec  6 08:48:17 PST 2019
#
# For information describing how to configure the Cloudera Manager Server
# to connect to databases, see the "Cloudera Manager Installation Guide."
#
com.cloudera.cmf.db.type=mysql
com.cloudera.cmf.db.host=harshalchg-2.gce.cloudera.com
com.cloudera.cmf.db.name=scm
com.cloudera.cmf.db.user=scm
com.cloudera.cmf.db.setupType=EXTERNAL
com.cloudera.cmf.db.password=scm
[root@harshalchg-4 ~]# 




....


