....
== user creation for Harshal
(base) MacBook-Pro-6:labs harshalpatil$ ssh root@172.31.116.204
root@172.31.116.204's password: 
Last login: Mon Dec  2 17:18:56 2019 from 10.96.92.195
-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
[root@harshalinstalllab-1 ~]# user add harshal
-bash: user: command not found
[root@harshalinstalllab-1 ~]# useradd harshal

[root@harshalinstalllab-1 ~]# passwd harshal
Changing password for user harshal.
New password: 
Retype new password: 
passwd: all authentication tokens updated successfully.

[root@harshalinstalllab-5 ~]# pssh -v -h ~/clhost -l root -A -i "adduser harshal"
Warning: do not enter your password if anyone else has superuser
privileges or access to your account.
Password: 
[1] 11:32:51 [FAILURE] 172.31.116.204 Exited with error code 9
Stderr: pssh-askpass received prompt: "root@172.31.116.204's password: "
adduser: user 'harshal' already exists
[2] 11:32:51 [SUCCESS] 172.31.116.202
Stderr: pssh-askpass received prompt: "root@172.31.116.202's password: "
[3] 11:32:51 [SUCCESS] 172.31.116.203
Stderr: pssh-askpass received prompt: "root@172.31.116.203's password: "
[4] 11:32:52 [SUCCESS] 172.31.116.206
Stderr: pssh-askpass received prompt: "root@172.31.116.206's password: "
[5] 11:32:52 [SUCCESS] 172.31.116.207
Stderr: pssh-askpass received prompt: "root@172.31.116.207's password: "
[root@harshalinstalllab-5 ~]# pssh -v -h ~/clhost -l root -A -i "echo cloudera > passwd harshal"
Warning: do not enter your password if anyone else has superuser
privileges or access to your account.
Password: 
[1] 11:33:27 [SUCCESS] 172.31.116.203
Stderr: pssh-askpass received prompt: "root@172.31.116.203's password: "
[2] 11:33:27 [SUCCESS] 172.31.116.204
Stderr: pssh-askpass received prompt: "root@172.31.116.204's password: "
[3] 11:33:27 [SUCCESS] 172.31.116.206
Stderr: pssh-askpass received prompt: "root@172.31.116.206's password: "
[4] 11:33:27 [SUCCESS] 172.31.116.207
Stderr: pssh-askpass received prompt: "root@172.31.116.207's password: "
[5] 11:33:27 [SUCCESS] 172.31.116.202
Stderr: pssh-askpass received prompt: "root@172.31.116.202's password: "
[root@harshalinstalllab-5 ~]# exit






== tergen to get 10GB file in Harshal

[hdfs@harshalinstalllab-5 root]$ hadoop jar /opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar teragen 100000000 /user/harshal/.
java.io.IOException: Output directory /user/harshal/ already exists.
	at org.apache.hadoop.examples.terasort.TeraGen.run(TeraGen.java:293)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.examples.terasort.TeraGen.main(TeraGen.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
	at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
	at org.apache.hadoop.examples.ExampleDriver.main(ExampleDriver.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:226)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:141)
[hdfs@harshalinstalllab-5 root]$ hadoop jar /opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar teragen 100000000 /user/harshal/teragen10gb
19/12/03 11:59:39 INFO client.RMProxy: Connecting to ResourceManager at harshalinstalllab-1.gce.cloudera.com/172.31.116.204:8032
19/12/03 11:59:40 INFO terasort.TeraGen: Generating 100000000 using 2
19/12/03 11:59:40 INFO mapreduce.JobSubmitter: number of splits:2
19/12/03 11:59:40 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1575336507718_0005
19/12/03 11:59:41 INFO impl.YarnClientImpl: Submitted application application_1575336507718_0005
19/12/03 11:59:41 INFO mapreduce.Job: The url to track the job: http://harshalinstalllab-1.gce.cloudera.com:8088/proxy/application_1575336507718_0005/
19/12/03 11:59:41 INFO mapreduce.Job: Running job: job_1575336507718_0005
19/12/03 11:59:48 INFO mapreduce.Job: Job job_1575336507718_0005 running in uber mode : false
19/12/03 11:59:48 INFO mapreduce.Job:  map 0% reduce 0%
19/12/03 12:00:09 INFO mapreduce.Job:  map 8% reduce 0%
19/12/03 12:00:14 INFO mapreduce.Job:  map 11% reduce 0%
19/12/03 12:00:15 INFO mapreduce.Job:  map 14% reduce 0%
19/12/03 12:00:20 INFO mapreduce.Job:  map 17% reduce 0%
19/12/03 12:00:21 INFO mapreduce.Job:  map 19% reduce 0%
19/12/03 12:00:26 INFO mapreduce.Job:  map 22% reduce 0%
19/12/03 12:00:27 INFO mapreduce.Job:  map 24% reduce 0%
19/12/03 12:00:32 INFO mapreduce.Job:  map 29% reduce 0%
19/12/03 12:00:39 INFO mapreduce.Job:  map 35% reduce 0%
19/12/03 12:00:45 INFO mapreduce.Job:  map 41% reduce 0%
19/12/03 12:00:50 INFO mapreduce.Job:  map 44% reduce 0%
19/12/03 12:00:51 INFO mapreduce.Job:  map 47% reduce 0%
19/12/03 12:00:56 INFO mapreduce.Job:  map 50% reduce 0%
19/12/03 12:00:57 INFO mapreduce.Job:  map 54% reduce 0%
19/12/03 12:01:02 INFO mapreduce.Job:  map 57% reduce 0%
19/12/03 12:01:03 INFO mapreduce.Job:  map 60% reduce 0%
19/12/03 12:01:09 INFO mapreduce.Job:  map 66% reduce 0%
19/12/03 12:01:15 INFO mapreduce.Job:  map 72% reduce 0%
19/12/03 12:01:21 INFO mapreduce.Job:  map 78% reduce 0%
19/12/03 12:01:26 INFO mapreduce.Job:  map 81% reduce 0%
19/12/03 12:01:27 INFO mapreduce.Job:  map 84% reduce 0%
19/12/03 12:01:33 INFO mapreduce.Job:  map 87% reduce 0%
19/12/03 12:01:34 INFO mapreduce.Job:  map 90% reduce 0%
19/12/03 12:01:39 INFO mapreduce.Job:  map 96% reduce 0%
19/12/03 12:01:43 INFO mapreduce.Job:  map 98% reduce 0%
19/12/03 12:01:44 INFO mapreduce.Job:  map 100% reduce 0%
19/12/03 12:01:44 INFO mapreduce.Job: Job job_1575336507718_0005 completed successfully
19/12/03 12:01:44 INFO mapreduce.Job: Counters: 31
	File System Counters
		FILE: Number of bytes read=0
		FILE: Number of bytes written=298754
		FILE: Number of read operations=0
		FILE: Number of large read operations=0
		FILE: Number of write operations=0
		HDFS: Number of bytes read=170
		HDFS: Number of bytes written=10000000000
		HDFS: Number of read operations=8
		HDFS: Number of large read operations=0
		HDFS: Number of write operations=4
	Job Counters 
		Launched map tasks=2
		Other local map tasks=2
		Total time spent by all maps in occupied slots (ms)=225585
		Total time spent by all reduces in occupied slots (ms)=0
		Total time spent by all map tasks (ms)=225585
		Total vcore-milliseconds taken by all map tasks=225585
		Total megabyte-milliseconds taken by all map tasks=230999040
	Map-Reduce Framework
		Map input records=100000000
		Map output records=100000000
		Input split bytes=170
		Spilled Records=0
		Failed Shuffles=0
		Merged Map outputs=0
		GC time elapsed (ms)=1401
		CPU time spent (ms)=160580
		Physical memory (bytes) snapshot=776224768
		Virtual memory (bytes) snapshot=5563666432
		Total committed heap usage (bytes)=729808896
	org.apache.hadoop.examples.terasort.TeraGen$Counters
		CHECKSUM=214760662691937609
	File Input Format Counters 
		Bytes Read=0
	File Output Format Counters 
		Bytes Written=10000000000



== terasort

[hdfs@harshalinstalllab-5 root]$ hadoop jar /opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar terasort  /user/harshal/teragen10gb /user/harshal/terasort1
19/12/03 12:06:28 INFO terasort.TeraSort: starting
19/12/03 12:06:30 INFO input.FileInputFormat: Total input paths to process : 2
Spent 166ms computing base-splits.
Spent 4ms computing TeraScheduler splits.
Computing input splits took 171ms
Sampling 10 splits of 76
Making 4 from 100000 sampled records
Computing parititions took 1108ms
Spent 1282ms computing partitions.
19/12/03 12:06:31 INFO client.RMProxy: Connecting to ResourceManager at harshalinstalllab-1.gce.cloudera.com/172.31.116.204:8032
19/12/03 12:06:32 INFO mapreduce.JobSubmitter: number of splits:76
19/12/03 12:06:32 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1575336507718_0006
19/12/03 12:06:32 INFO impl.YarnClientImpl: Submitted application application_1575336507718_0006
19/12/03 12:06:32 INFO mapreduce.Job: The url to track the job: http://harshalinstalllab-1.gce.cloudera.com:8088/proxy/application_1575336507718_0006/
19/12/03 12:06:32 INFO mapreduce.Job: Running job: job_1575336507718_0006
19/12/03 12:06:39 INFO mapreduce.Job: Job job_1575336507718_0006 running in uber mode : false
19/12/03 12:06:39 INFO mapreduce.Job:  map 0% reduce 0%
19/12/03 12:06:52 INFO mapreduce.Job:  map 1% reduce 0%
19/12/03 12:06:55 INFO mapreduce.Job:  map 4% reduce 0%
19/12/03 12:06:57 INFO mapreduce.Job:  map 8% reduce 0%
19/12/03 12:06:58 INFO mapreduce.Job:  map 9% reduce 0%
19/12/03 12:07:02 INFO mapreduce.Job:  map 11% reduce 0%
19/12/03 12:07:09 INFO mapreduce.Job:  map 13% reduce 0%
19/12/03 12:07:12 INFO mapreduce.Job:  map 16% reduce 0%
19/12/03 12:07:13 INFO mapreduce.Job:  map 20% reduce 0%
19/12/03 12:07:23 INFO mapreduce.Job:  map 24% reduce 0%
19/12/03 12:07:29 INFO mapreduce.Job:  map 29% reduce 0%
19/12/03 12:07:34 INFO mapreduce.Job:  map 30% reduce 0%
19/12/03 12:07:37 INFO mapreduce.Job:  map 33% reduce 0%
19/12/03 12:07:44 INFO mapreduce.Job:  map 34% reduce 0%
19/12/03 12:07:45 INFO mapreduce.Job:  map 37% reduce 0%
19/12/03 12:07:47 INFO mapreduce.Job:  map 39% reduce 0%
19/12/03 12:07:51 INFO mapreduce.Job:  map 42% reduce 0%
19/12/03 12:07:54 INFO mapreduce.Job:  map 43% reduce 0%
19/12/03 12:08:01 INFO mapreduce.Job:  map 46% reduce 0%
19/12/03 12:08:06 INFO mapreduce.Job:  map 50% reduce 0%
19/12/03 12:08:07 INFO mapreduce.Job:  map 51% reduce 0%
19/12/03 12:08:08 INFO mapreduce.Job:  map 53% reduce 0%
19/12/03 12:08:17 INFO mapreduce.Job:  map 57% reduce 0%
19/12/03 12:08:20 INFO mapreduce.Job:  map 59% reduce 0%
19/12/03 12:08:27 INFO mapreduce.Job:  map 63% reduce 0%
19/12/03 12:08:33 INFO mapreduce.Job:  map 64% reduce 0%
19/12/03 12:08:34 INFO mapreduce.Job:  map 68% reduce 0%
19/12/03 12:08:38 INFO mapreduce.Job:  map 70% reduce 0%
19/12/03 12:08:45 INFO mapreduce.Job:  map 72% reduce 0%
19/12/03 12:08:47 INFO mapreduce.Job:  map 74% reduce 0%
19/12/03 12:08:48 INFO mapreduce.Job:  map 75% reduce 0%
19/12/03 12:08:49 INFO mapreduce.Job:  map 78% reduce 0%
19/12/03 12:08:50 INFO mapreduce.Job:  map 79% reduce 0%
19/12/03 12:08:59 INFO mapreduce.Job:  map 80% reduce 0%
19/12/03 12:09:01 INFO mapreduce.Job:  map 83% reduce 0%
19/12/03 12:09:02 INFO mapreduce.Job:  map 86% reduce 0%
19/12/03 12:09:05 INFO mapreduce.Job:  map 87% reduce 0%
19/12/03 12:09:06 INFO mapreduce.Job:  map 88% reduce 0%
19/12/03 12:09:09 INFO mapreduce.Job:  map 89% reduce 0%
19/12/03 12:09:17 INFO mapreduce.Job:  map 91% reduce 0%
19/12/03 12:09:18 INFO mapreduce.Job:  map 92% reduce 0%
19/12/03 12:09:20 INFO mapreduce.Job:  map 92% reduce 8%
19/12/03 12:09:21 INFO mapreduce.Job:  map 93% reduce 8%
19/12/03 12:09:22 INFO mapreduce.Job:  map 95% reduce 8%
19/12/03 12:09:26 INFO mapreduce.Job:  map 95% reduce 12%
19/12/03 12:09:27 INFO mapreduce.Job:  map 95% reduce 14%
19/12/03 12:09:28 INFO mapreduce.Job:  map 96% reduce 14%
19/12/03 12:09:32 INFO mapreduce.Job:  map 96% reduce 16%
19/12/03 12:09:33 INFO mapreduce.Job:  map 97% reduce 19%
19/12/03 12:09:35 INFO mapreduce.Job:  map 99% reduce 19%
19/12/03 12:09:38 INFO mapreduce.Job:  map 99% reduce 21%
19/12/03 12:09:39 INFO mapreduce.Job:  map 100% reduce 23%
19/12/03 12:09:44 INFO mapreduce.Job:  map 100% reduce 38%
19/12/03 12:09:45 INFO mapreduce.Job:  map 100% reduce 57%
19/12/03 12:09:50 INFO mapreduce.Job:  map 100% reduce 62%
19/12/03 12:09:51 INFO mapreduce.Job:  map 100% reduce 64%
19/12/03 12:09:56 INFO mapreduce.Job:  map 100% reduce 76%
19/12/03 12:09:57 INFO mapreduce.Job:  map 100% reduce 78%
19/12/03 12:10:02 INFO mapreduce.Job:  map 100% reduce 83%
19/12/03 12:10:03 INFO mapreduce.Job:  map 100% reduce 85%
19/12/03 12:10:07 INFO mapreduce.Job:  map 100% reduce 86%
19/12/03 12:10:08 INFO mapreduce.Job:  map 100% reduce 90%
19/12/03 12:10:09 INFO mapreduce.Job:  map 100% reduce 92%
19/12/03 12:10:13 INFO mapreduce.Job:  map 100% reduce 95%
19/12/03 12:10:15 INFO mapreduce.Job:  map 100% reduce 96%
19/12/03 12:10:19 INFO mapreduce.Job:  map 100% reduce 98%
19/12/03 12:10:25 INFO mapreduce.Job:  map 100% reduce 99%
19/12/03 12:10:28 INFO mapreduce.Job:  map 100% reduce 100%
19/12/03 12:10:28 INFO mapreduce.Job: Job job_1575336507718_0006 completed successfully
19/12/03 12:10:28 INFO mapreduce.Job: Counters: 49
	File System Counters
		FILE: Number of bytes read=4464016260
		FILE: Number of bytes written=8846930625
		FILE: Number of read operations=0
		FILE: Number of large read operations=0
		FILE: Number of write operations=0
		HDFS: Number of bytes read=10000011476
		HDFS: Number of bytes written=10000000000
		HDFS: Number of read operations=240
		HDFS: Number of large read operations=0
		HDFS: Number of write operations=8
	Job Counters 
		Launched map tasks=76
		Launched reduce tasks=4
		Data-local map tasks=76
		Total time spent by all maps in occupied slots (ms)=1029903
		Total time spent by all reduces in occupied slots (ms)=264151
		Total time spent by all map tasks (ms)=1029903
		Total time spent by all reduce tasks (ms)=264151
		Total vcore-milliseconds taken by all map tasks=1029903
		Total vcore-milliseconds taken by all reduce tasks=264151
		Total megabyte-milliseconds taken by all map tasks=1054620672
		Total megabyte-milliseconds taken by all reduce tasks=270490624
	Map-Reduce Framework
		Map input records=100000000
		Map output records=100000000
		Map output bytes=10200000000
		Map output materialized bytes=4370835475
		Input split bytes=11476
		Combine input records=0
		Combine output records=0
		Reduce input groups=100000000
		Reduce shuffle bytes=4370835475
		Reduce input records=100000000
		Reduce output records=100000000
		Spilled Records=200000000
		Shuffled Maps =304
		Failed Shuffles=0
		Merged Map outputs=304
		GC time elapsed (ms)=25696
		CPU time spent (ms)=946110
		Physical memory (bytes) snapshot=43152277504
		Virtual memory (bytes) snapshot=222901719040
		Total committed heap usage (bytes)=43807408128
	Shuffle Errors
		BAD_ID=0
		CONNECTION=0
		IO_ERROR=0
		WRONG_LENGTH=0
		WRONG_MAP=0
		WRONG_REDUCE=0
	File Input Format Counters 
		Bytes Read=10000000000
	File Output Format Counters 
		Bytes Written=10000000000
19/12/03 12:10:28 INFO terasort.TeraSort: done
[hdfs@harshalinstalllab-5 root]$ hadoop jar /opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar teragen  --help
teragen <num rows> <output dir>
[hdfs@harshalinstalllab-5 root]$ 




